<?php
/**
 * @file
 * Drupal needs this blank file.
 */

include_once 'kaveret_offer.features.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */
function kaveret_offer_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_form_alter().
 *
 * Alter the node form of request and offer.
 */
function kaveret_offer_form_alter(&$form, &$form_state, $form_id) {
  if (!in_array($form_id, array('offer_node_form', 'request_node_form'))) {
    return;
  }

  $node = $form_state['node'];
  if (empty($node->nid)) {
    // Allow overriding the type.
    drupal_set_title($node->type == 'request' ? t('I would like to request') : t('I would like to offer'));
  }

  // The expiry label is different on the node view because there we display a
  // specific date.
  $form['field_expiry_after'][LANGUAGE_NONE]['#title'] = t('Delete after');
  $form['field_expiry_after'][LANGUAGE_NONE]['#options']['_none'] = t('Never');
}

/**
 * Implements hook_field_formatter_info().
 */
function kaveret_offer_field_formatter_info() {
  return array(
    'expiry_date' => array(
      'label' => t('Expiry date'),
      'field types' => array('list_text'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function kaveret_offer_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();

  switch ($display['type']) {
    case 'expiry_date':
      // Ignore expiry date: "Never".
      if (empty($items[0]['value'])) {
        break;
      }

      // Calculate the expiry date by applying the expiry_after value (E.g.
      // "+1 day") to the time the node was updated.
      $expiry_date = strtotime($items[0]['value'], $entity->changed);
      // Format the date.
      $expiry_date = date(variable_get('date_format_short'), $expiry_date);

      $element[0] = array('#markup' => $expiry_date);
      break;
  }

  return $element;
}

/**
 * Implements hook_comment_presave().
 *
 * Save update the node status according to the setting on the comment.
 */
function kaveret_offer_comment_presave($comment) {
  $wrapper = entity_metadata_wrapper('comment', $comment);
  $node = $wrapper->node->value();

  $save = FALSE;

  // Set the values from the comment on the task.
  foreach (garmentbox_task_intersect_fields() as $field_name => $field_info) {
    $value = _garmentbox_task_comment_extract_value($comment, $field_info, $field_name);
    $original_value = _garmentbox_task_comment_extract_value($node, $field_info, $field_name);
    // Check if the field was changed on the comment.
    if ($value != $original_value) {
      $save = TRUE;
      $wrapper->node->$field_name->set($value);
    }
  }

  if (!$save) {
    return;
  }

  // Set the revision ID to the node ID before it is saved.
  $wrapper->field_revision_id->set($node->vid);

  $node->revision = TRUE;
  node_save($node);
}
